version: '3.8'

services:
  db:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network
  
  api:
    image: api-service:dev-1.0
    container_name: api
    ports:
      - "8632:8000"
    volumes:
      - ./api-services:/app/src/shared/data
    depends_on:
      - db
    networks:
      - app-network
  
  fe:
    image: frontend-service:dev-1.0
    container_name: fe
    ports:
      - "8633:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge