version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: persondb
    networks:
      - app-network
  
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: api-service:dev-1.0
    container_name: api
    ports:
      - "8632:8000"
    volumes:
      - ../data/api-services:/api/src/shared/data
    depends_on:
      - db
    networks:
      - app-network
  
  fe:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend-service:dev-1.0
    container_name: fe
    ports:
      - "8633:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge